CREATE TABLE IF NOT EXISTS command_history (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at_ms BIGINT NOT NULL,
    robot_slug TEXT,
    source TEXT NOT NULL,
    status TEXT NOT NULL,
    accepted_latency_ms BIGINT,
    payload_json TEXT NOT NULL,
    user_id TEXT,
    display_name TEXT
);

CREATE INDEX IF NOT EXISTS command_history_created_idx
    ON command_history(created_at_ms DESC);

CREATE INDEX IF NOT EXISTS command_history_robot_idx
    ON command_history(robot_slug, created_at_ms DESC);
