-- Expand legacy runtime schema without dropping SQLite source data.

CREATE TABLE IF NOT EXISTS command_history (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                created_at_ms BIGINT NOT NULL,
                robot_slug TEXT,
                source TEXT NOT NULL,
                status TEXT NOT NULL,
                accepted_latency_ms BIGINT,
                payload_json TEXT NOT NULL
            );

CREATE INDEX IF NOT EXISTS command_history_created_idx ON command_history(created_at_ms DESC);

CREATE INDEX IF NOT EXISTS command_history_robot_idx ON command_history(robot_slug, created_at_ms DESC);

CREATE TABLE IF NOT EXISTS web_auth_sessions (
                token_hash TEXT PRIMARY KEY,
                sub TEXT,
                username TEXT,
                display_name TEXT,
                role TEXT,
                provider TEXT,
                created_at_ms BIGINT NOT NULL,
                expires_at_ms BIGINT NOT NULL
            );

CREATE INDEX IF NOT EXISTS web_auth_sessions_expiry_idx ON web_auth_sessions(expires_at_ms);

CREATE TABLE IF NOT EXISTS user_robot_binding (
                user_id TEXT NOT NULL,
                robot_slug TEXT NOT NULL,
                display_name TEXT,
                permission TEXT NOT NULL DEFAULT 'operator',
                created_at_ms BIGINT NOT NULL,
                PRIMARY KEY (user_id, robot_slug)
            );

CREATE INDEX IF NOT EXISTS user_robot_binding_user_idx ON user_robot_binding(user_id);

CREATE TABLE IF NOT EXISTS scenario_runs (
                run_id TEXT PRIMARY KEY,
                scenario_id TEXT NOT NULL,
                scenario_version TEXT NOT NULL,
                robot_slug TEXT NOT NULL,
                source TEXT NOT NULL,
                idempotency_key TEXT NOT NULL,
                risk_level TEXT NOT NULL,
                state TEXT NOT NULL,
                parameters_json TEXT NOT NULL,
                created_at_ms BIGINT NOT NULL,
                updated_at_ms BIGINT NOT NULL,
                UNIQUE(robot_slug, idempotency_key)
            );

CREATE INDEX IF NOT EXISTS scenario_runs_robot_created_idx ON scenario_runs(robot_slug, created_at_ms DESC);

CREATE TABLE IF NOT EXISTS scenario_run_events (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                run_id TEXT NOT NULL,
                created_at_ms BIGINT NOT NULL,
                state TEXT NOT NULL,
                source TEXT NOT NULL
            );

CREATE INDEX IF NOT EXISTS scenario_run_events_run_idx ON scenario_run_events(run_id, id ASC);

CREATE TABLE IF NOT EXISTS calibrated_routes (
                route_id TEXT PRIMARY KEY,
                version TEXT NOT NULL,
                title TEXT NOT NULL,
                segments_json TEXT NOT NULL,
                updated_at_ms BIGINT NOT NULL
            );

CREATE TABLE IF NOT EXISTS calibrated_route_runs (
                route_run_id TEXT PRIMARY KEY,
                route_id TEXT NOT NULL,
                robot_slug TEXT NOT NULL,
                idempotency_key TEXT NOT NULL,
                current_segment BIGINT NOT NULL,
                state TEXT NOT NULL,
                active_scenario_run_id TEXT,
                operation_permit_id TEXT,
                created_at_ms BIGINT NOT NULL,
                updated_at_ms BIGINT NOT NULL,
                UNIQUE(robot_slug, idempotency_key)
            );

CREATE TABLE IF NOT EXISTS calibrated_route_recoveries (
                route_run_id TEXT PRIMARY KEY,
                recovery_required_at_ms BIGINT NOT NULL,
                recovered_at_ms BIGINT,
                operator_name TEXT,
                action TEXT,
                note TEXT NOT NULL DEFAULT ''
            );

CREATE TABLE IF NOT EXISTS calibrated_route_certifications (
                route_id TEXT PRIMARY KEY,
                route_version TEXT NOT NULL,
                certified_at_ms BIGINT NOT NULL,
                operator_name TEXT NOT NULL,
                checks_json TEXT NOT NULL
            );

CREATE TABLE IF NOT EXISTS autonomy_authorizations (
                authorization_id TEXT PRIMARY KEY,
                operator_name TEXT NOT NULL,
                role TEXT NOT NULL,
                scopes_json TEXT NOT NULL,
                issued_at_ms BIGINT NOT NULL,
                expires_at_ms BIGINT NOT NULL,
                revoked_at_ms BIGINT,
                note TEXT NOT NULL DEFAULT ''
            );

CREATE TABLE IF NOT EXISTS calibrated_route_releases (
                route_id TEXT PRIMARY KEY,
                route_version TEXT NOT NULL,
                state TEXT NOT NULL,
                approved_by_authorization_id TEXT NOT NULL,
                allowed_robots_json TEXT NOT NULL,
                updated_at_ms BIGINT NOT NULL,
                note TEXT NOT NULL DEFAULT ''
            );

CREATE TABLE IF NOT EXISTS robot_localization_attestations (
                robot_slug TEXT PRIMARY KEY,
                map_id TEXT NOT NULL,
                map_version TEXT NOT NULL,
                attested_at_ms BIGINT NOT NULL,
                operator_name TEXT NOT NULL,
                checks_json TEXT NOT NULL
            );

CREATE TABLE IF NOT EXISTS robot_safety_envelopes (
                robot_slug TEXT PRIMARY KEY,
                attested_at_ms BIGINT NOT NULL,
                operator_name TEXT NOT NULL,
                checks_json TEXT NOT NULL
            );

CREATE TABLE IF NOT EXISTS autonomy_zone_reservations (
                reservation_id TEXT PRIMARY KEY,
                zone_id TEXT NOT NULL UNIQUE,
                robot_slug TEXT NOT NULL,
                route_id TEXT NOT NULL,
                created_at_ms BIGINT NOT NULL,
                expires_at_ms BIGINT NOT NULL,
                released_at_ms BIGINT
            );

CREATE TABLE IF NOT EXISTS autonomy_fault_drills (
                drill_id TEXT PRIMARY KEY,
                robot_slug TEXT NOT NULL,
                completed_at_ms BIGINT NOT NULL,
                operator_name TEXT NOT NULL,
                checks_json TEXT NOT NULL
            );

CREATE TABLE IF NOT EXISTS autonomy_operation_permits (
                permit_id TEXT PRIMARY KEY,
                route_id TEXT NOT NULL,
                route_version TEXT NOT NULL,
                robot_slug TEXT NOT NULL,
                zone_reservation_id TEXT NOT NULL,
                authorization_id TEXT NOT NULL,
                issued_at_ms BIGINT NOT NULL,
                expires_at_ms BIGINT NOT NULL,
                revoked_at_ms BIGINT,
                note TEXT NOT NULL DEFAULT ''
            );

CREATE TABLE IF NOT EXISTS autonomy_alerts (
                alert_id TEXT PRIMARY KEY,
                robot_slug TEXT NOT NULL,
                level TEXT NOT NULL,
                code TEXT NOT NULL,
                message TEXT NOT NULL,
                created_at_ms BIGINT NOT NULL,
                resolved_at_ms BIGINT
            );

CREATE INDEX IF NOT EXISTS autonomy_alerts_open_idx ON autonomy_alerts(resolved_at_ms, created_at_ms DESC);

CREATE TABLE IF NOT EXISTS music_playlists (
                playlist_id TEXT PRIMARY KEY,
                version TEXT NOT NULL,
                title TEXT NOT NULL,
                mood TEXT NOT NULL,
                tracks_json TEXT NOT NULL,
                updated_at_ms BIGINT NOT NULL
            );

CREATE TABLE IF NOT EXISTS scenario_definitions (
                scenario_id TEXT PRIMARY KEY,
                version TEXT NOT NULL,
                title TEXT NOT NULL,
                description TEXT NOT NULL,
                risk_level TEXT NOT NULL,
                confirmation TEXT NOT NULL,
                required_capabilities_json TEXT NOT NULL,
                command_json TEXT NOT NULL,
                updated_at_ms BIGINT NOT NULL
            );

CREATE TABLE IF NOT EXISTS robot_field_attestations (
                robot_slug TEXT PRIMARY KEY,
                attested_at_ms BIGINT NOT NULL,
                operator_name TEXT NOT NULL,
                checks_json TEXT NOT NULL
            );

ALTER TABLE scenario_definitions ADD COLUMN IF NOT EXISTS created_by TEXT;
ALTER TABLE scenario_definitions ADD COLUMN IF NOT EXISTS source TEXT DEFAULT 'system';
